"""Correct model

Revision ID: e6cc99e72275
Revises: 
Create Date: 2024-11-15 01:27:22.129048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cc99e72275'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('btc_usdt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('utc_time', sa.DateTime(), nullable=False),
    sa.Column('msc_time', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msc_time'),
    sa.UniqueConstraint('timestamp'),
    sa.UniqueConstraint('utc_time')
    )
    op.create_index(op.f('ix_btc_usdt_id'), 'btc_usdt', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_btc_usdt_id'), table_name='btc_usdt')
    op.drop_table('btc_usdt')
    # ### end Alembic commands ###
